# Enable the subsequent settings only in interactive sessions
case $- in
  *i*) ;;
    *) return;;
esac

# Path to your oh-my-bash installation.
export OSH='/home/r/.oh-my-bash'

OSH_THEME="font"

# Uncomment the following line to use case-sensitive completion.
# OMB_CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# OMB_HYPHEN_SENSITIVE="false"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_OSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.  One of the following values can
# be used to specify the timestamp format.
# * 'mm/dd/yyyy'     # mm/dd/yyyy + time
# * 'dd.mm.yyyy'     # dd.mm.yyyy + time
# * 'yyyy-mm-dd'     # yyyy-mm-dd + time
# * '[mm/dd/yyyy]'   # [mm/dd/yyyy] + [time] with colors
# * '[dd.mm.yyyy]'   # [dd.mm.yyyy] + [time] with colors
# * '[yyyy-mm-dd]'   # [yyyy-mm-dd] + [time] with colors
# If not set, the default value is 'yyyy-mm-dd'.
# HIST_STAMPS='yyyy-mm-dd'

# Uncomment the following line if you do not want OMB to overwrite the existing
# aliases by the default OMB aliases defined in lib/*.sh
# OMB_DEFAULT_ALIASES="check"

# Would you like to use another custom folder than $OSH/custom?
# OSH_CUSTOM=/path/to/new-custom-folder

# To disable the uses of "sudo" by oh-my-bash, please set "false" to
# this variable.  The default behavior for the empty value is "true".
OMB_USE_SUDO=true

# To enable/disable display of Python virtualenv and condaenv
# OMB_PROMPT_SHOW_PYTHON_VENV=true  # enable
# OMB_PROMPT_SHOW_PYTHON_VENV=false # disable

# Which completions would you like to load? (completions can be found in ~/.oh-my-bash/completions/*)
# Custom completions may be added to ~/.oh-my-bash/custom/completions/
# Example format: completions=(ssh git bundler gem pip pip3)
# Add wisely, as too many completions slow down shell startup.
completions=(
  git
  composer
  ssh
)

# Which aliases would you like to load? (aliases can be found in ~/.oh-my-bash/aliases/*)
# Custom aliases may be added to ~/.oh-my-bash/custom/aliases/
# Example format: aliases=(vagrant composer git-avh)
# Add wisely, as too many aliases slow down shell startup.
aliases=(
  general
)

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-bash/plugins/*)
# Custom plugins may be added to ~/.oh-my-bash/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  bashmarks
)

# Which plugins would you like to conditionally load? (plugins can be found in ~/.oh-my-bash/plugins/*)
# Custom plugins may be added to ~/.oh-my-bash/custom/plugins/
# Example format: 
#  if [ "$DISPLAY" ] || [ "$SSH" ]; then
#      plugins+=(tmux-autoattach)
#  fi

source "$OSH"/oh-my-bash.sh;
# # Personal Aliases

alias cat="bat"
alias catt="/bin/cat"
alias dl="cd ~/Downloads"
alias doc="cd ~/Documents"
alias hack="cd ~/HACK"
alias htb="sudo openvpn /home/r/HACK/hackthebox/openvpn/lab_xrrx.ovpn"
alias tryhackme="sudo openvpn /home/r/HACK/tryhackme/openvpn/0xe7272e.ovpn"
alias hosts="sudo vim /etc/hosts"
alias htbdir="cd ~/HACK/htb"
alias config="vim ~/Documents/config-files/update_config"
alias wargame="cd ~/HACK/Wargames"
alias copy="xclip -sel clip"
alias minecraft="java -jar -Xmx1024M -Xms1024M   ~/Documents/minecraft/TLauncher-2.86.jar"
alias xonsh="/home/r/.local/bin/xonsh"
alias shutdown="/usr/sbin/shutdown"
alias reboot="/usr/sbin/reboot"
alias ifconfig="/usr/sbin/ifconfig"
alias wow="echo 'abriendo wow' ; wine /home/r/Documents/wow/Wow.exe"
alias labb="lab  | grep 'next lab'  | cut -d ' ' -f 4-  | xclip -sel clip ; echo copied ; xclip -sel clip -o"
alias labr="lab -r  | grep 'next lab'  | cut -d ' ' -f 4-  | xclip -sel clip ; xclip -sel clip -o"
alias rustscan="/home/r/.cargo/bin/rustscan"
alias gf="gf"
alias donde="anonsurf myip"
alias edwin="ssh malw@ssh.nvidia.saturnenterprise.io"
# alias anon="echo 'stopping tor service... '; sudo systemctl stop tor ;echo 'starting tor service...';  sudo torctl start ; anonsurf myip"
alias noanon="echo 'getting out from tor'; sudo torctl stop ;echo 'starting tor daemon';  sudo systemctl start tor ; anonsurf myip "
alias changeip='sudo torctl chngid; donde'
alias toribash="bash /home/r/Documents/toribash/toribash"


# Administrando servidores
alias tank="ssh r@192.168.0.11"
alias tank_remote="ssh r@6.tcp.ngrok.io -p 19359"
alias mini="ssh r@192.168.0.9"
alias mini_remote="ssh r@4.tcp.ngrok.io -p 18958"
alias bext="ssh r@192.168.0.4"
alias crontab="EDITOR=vim crontab -e"

# Tmux Stuff
# tmux attach > /dev/null 2>&1 || tmux new > /dev/null 2>&1

# Terminal in vim mode
set -o vi;
# PATH
export PATH=$PATH:/usr/local/go/bin:/usr/local/julia-1.8.0/bin:/home/r/Documents/anaconda/bin:/home/r/.local/bin:/snap/bin:/usr/sbin:/home/r/go/bin:/home/r/Documents/smuggler:/home/r/Documents/wordlistctl:/home/r/Documents/nmap2md
