export ZSH="$HOME/.oh-my-zsh"
#ZSH_THEME="robbyrussell"
ZSH_THEME="skaro"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Path
export PATH=$PATH:/usr/local/go/bin:/usr/local/julia-1.8.0/bin:/home/r/Documents/anaconda/bin:/home/r/.local/bin:/snap/bin:/usr/sbin:/home/r/go/bin:/home/r/Documents/smuggler:/home/r/Documents/wordlistctl:/home/r/Documents/nmap2md:/home/r/.cargo/bin

# Personal Aliases

alias cat="bat"
alias catt="/bin/cat"
alias dl="cd ~/Downloads"
alias doc="cd ~/Documents"
alias hack="cd ~/HACK"
alias minecraft="java -jar -Xmx1024M -Xms1024M   ~/Documents/Games/minecraft/minecraft.jar"
alias xonsh="/home/r/.local/bin/xonsh"
alias shutdown="/usr/sbin/shutdown"
alias reboot="/usr/sbin/reboot"
alias ifconfig="/usr/sbin/ifconfig"
alias wow="echo 'abriendo wow' ; deepin-wine5-stable /home/r/Documents/Games/wow/Wow.exe" # yay install
alias labb="lab  | grep 'next lab'  | cut -d ' ' -f 4-  | xclip -sel clip ; echo copied ; xclip -sel clip -o"
alias labr="lab -r  | grep 'next lab'  | cut -d ' ' -f 4-  | xclip -sel clip ; xclip -sel clip -o"
alias rustscan="/home/r/.cargo/bin/rustscan"
alias genymotion="/home/r/Documents/genymotion/genymotion/genymotion"
alias changeip='sudo torctl chngid; donde'
alias toribash="bash /home/r/Documents/toribash/toribash"
alias jwt_tool="python /home/r/Documents/repos/jwt_tool/jwt_tool.py"
alias ls="lsd"
alias anon="sudo systemctl stop tor; curl ip.me ; sudo torctl start ; curl ip.me"
alias noanon="curl ip.me ; sudo torctl stop; sudo systemctl start tor ; curl ip.me"
alias icat="kitten icat"
alias tmp="cd /tmp"
alias stressgpu="glxgears"
alias qtconsole="jupyter qtconsole --style=monokai"
# flatpak install flathub com.stremio.Stremio 
alias update_music="bash ~/Documents/xqweak/fast_scripts/update_music.sh"
#
# Screen i3
#alias screen="bash ~/Documents/xqweak/fast_scripts/screenright.sh"
#alias single="bash ~/Documents/config_files_i3/single.sh"

# Termbin for http://termbin.com/
alias termbin="nc termbin.com 9999"

# Nmap2md /home/r/Documents/repos/nmap2md
alias nmap2md="python ~/Documents/repos/nmap2md/nmap2md.py"

# Auto Start Tmux
# tmux attach > /dev/null 2>&1 || tmux new > /dev/null 2>&1

# Terminal in vim mode
set -o vi

if [[ $TERM == xterm ]]; then TERM=xterm-256color; fi
#cat -pp  ~/.todo.md
/bin/cat ~/.todo.md
alias todo='vim ~/.todo.md'

# Exporto la API KEY de chaos
export CHAOS_KEY=$(cat ~/.chaos.txt)

# Open kitty in last path
chpwd() {
      echo $PWD > ~/.last_dir
}
